<?php
/**
 * This File is a part of the plesk-acronis extension (https://github.com/StratoAG/plesk-acronis)
 *
 * Created by Vincent Fahrenholz <fahrenholz@strato-rz.de>
 *
 * Date: 11.03.16
 * Time: 16:25
 *
 * Template for the action admin/list
 *
 * @licence http://www.apache.org/licenses/LICENSE-2.0 Apache Licence v. 2.0
 */

    echo $this->renderTools($this->toolbar);
?>
    <label for="simpleAuthorizationMode"><?php echo pm_Locale::lmsg('simpleAuthorizationModeLabel'); ?></label>
    <select id="simpleAuthorizationMode" data-rel="<?php echo $this->authorizationModeUrl?>" onchange="toggleAuthorizationMode(this)">
        <option
            value="extended"
            <?php
                if ($this->authorizationMode == 'extended') {
                    echo 'selected="selected"';
                }
            ?>
        >
            <?php echo pm_Locale::lmsg('simpleAuthorizationDisabled')?>
        </option>
        <option
            value="simple"
            <?php
                if ($this->authorizationMode == 'simple') {
                    echo 'selected="selected"';
                }
            ?>
        >
            <?php echo pm_Locale::lmsg('simpleAuthorizationEnabled')?>
        </option>
    </select>
<?php
    if ($this->authorizationMode == 'extended') {
        echo $this->renderList($this->list);
    }
?>
