<?php
/**
 * This File is a part of the plesk-acronis extension (https://github.com/StratoAG/plesk-acronis)
 *
 * Created by Vincent Fahrenholz <fahrenholz@strato-rz.de>
 *
 * Date: 11.03.16
 * Time: 16:25
 *
 * Template for the action customer/item
 *
 * @licence http://www.apache.org/licenses/LICENSE-2.0 Apache Licence v. 2.0
 */

?>
<p><?php echo pm_Locale::lmsg('customerItemIntro'); ?></p>

<h3><?php echo pm_Locale::lmsg('customerItemSubtitle'); ?></h3>
<div class="list-box">
    <table class="list">
        <tr>
            <th>
                <?php echo pm_Locale::lmsg('customerItemLabelDatetime'); ?>
            </th>
            <td>
                <?php echo date("M d, Y G:H", $this->item->datetime); ?>
            </td>
        </tr>

        <tr>
            <th>
                <?php echo pm_Locale::lmsg('customerItemLabelSize'); ?>
            </th>
            <td>
                <?php echo $this->item->size; ?>
            </td>
        </tr>
    </table>
</div>

<a class="btn action" href="<?php echo pm_Context::getActionUrl('customer', 'list'); ?>">
    <?php echo pm_Locale::lmsg('customerItemBack'); ?>
</a>
<a class="btn action" href="<?php echo pm_Context::getActionUrl('customer', 'restore'); ?>/<?php echo $this->item->id; ?>">
    <?php echo pm_Locale::lmsg('customerItemRestorebutton'); ?>
</a>