<?php echo $this->renderTools($this->tools);?>

<p>Of course, there will be content here. Dashboard, 3 components</p>
<ul>
    <li>Acronis Host
        <ul>
            <li>Is the host reachable?</li>
            <li>Configuration details</li>
        </ul>
    </li>
    <li>Backup Plans
        <ul>
            <li>all configured backup plans</li>
        </ul>
    </li>
    <li>Backup log
        <ul>
            <li>Last backups</li>
            <li>status</li>
        </ul>
    </li>
</ul>
